#pragma once

// Typy operacji
enum class FunctionType {
    NO_OPERATION,

    CHANGE_TASK_PROCESSOR_RANDOM,
    MOVE_TASK_TO_FASTEST_PP,
    MOVE_TASK_TO_FASTEST_HC,
    MOVE_TASK_TO_CHEAPEST_PP,
    MOVE_TASK_TO_CHEAPEST_HC,
    MOVE_TASK_TO_LEAST_BUSY_PP,
    BUY_RANDOM_PP,

    //     CHANGE_CHANNEL_RANDOM,
    //     MOVE_PROCESSOR_TO_BEST_BANDWIDTH_CHANNEL,
    //     MOVE_PROCESSOR_TO_CHEAPEST_CHANNEL,

    COUNT // funkcja do wyliczenia ilości funkcji
};
